[theme]
primaryColor = "#ff0000"          # Vermelho
backgroundColor = "#0f0f0f"       # Preto muito levemente claro
secondaryBackgroundColor = "#1f1f1f"  # Cinza escuro suavizado
textColor = "#f5f5f5"             # Branco com leve toque de cinza
font = "sans serif"
